import fs from 'fs';

import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

import { readEmbeddedMetadata } from '#src/image/metadata.js';
import { readMetadataSchema } from '#src/schemas.js';
import type { ReadMetadataInput } from '#src/schemas.js';

/**
 * Registers the `read_image_metadata` tool on the given MCP server.
 *
 * Reads the JSON metadata embedded in the EXIF ImageDescription of a PNG
 * that was produced by this server. Useful for non-vision models to
 * understand asset contents without loading the image pixels.
 */
export function registerReadMetadataTool(server: McpServer): void {
  server.registerTool(
    'read_image_metadata',
    {
      description:
        'Reads the embedded JSON metadata from a PNG file generated by this MCP server. Returns the metadata object with dimensions, color, shape, description, etc.',
      inputSchema: readMetadataSchema,
    },
    async (args) => {
      try {
        const { filepath } = args as ReadMetadataInput;

        if (!fs.existsSync(filepath)) {
          return {
            content: [{ type: 'text', text: `File not found: ${filepath}` }],
            isError: true,
          };
        }

        const meta = await readEmbeddedMetadata(filepath);

        if (!meta) {
          return {
            content: [
              {
                type: 'text',
                text: 'No embedded JSON metadata found in this image.',
              },
            ],
          };
        }

        return {
          content: [{ type: 'text', text: JSON.stringify(meta, null, 2) }],
        };
      } catch (error) {
        const err = error as Error;

        return {
          content: [
            { type: 'text', text: `Error reading metadata: ${err.message}` },
          ],
          isError: true,
        };
      }
    },
  );
}
